// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwMvIasJ_vKHMntyIAJYBqdHjNnhacVgI',
    appId: '1:707222535071:web:df509c884d2e24ef1e1baa',
    messagingSenderId: '707222535071',
    projectId: 'nazra-274ec',
    authDomain: 'nazra-274ec.firebaseapp.com',
    storageBucket: 'nazra-274ec.firebasestorage.app',
    measurementId: 'G-0XF4MHKMWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SRjaplI7FbHwG_xQgIzBO-wyWCHAsUs',
    appId: '1:707222535071:android:2804b08f65650c191e1baa',
    messagingSenderId: '707222535071',
    projectId: 'nazra-274ec',
    storageBucket: 'nazra-274ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMOHP1PD26iTy33HTyxIDd8gVnlE2U_4Y',
    appId: '1:707222535071:ios:22cb47652cda472f1e1baa',
    messagingSenderId: '707222535071',
    projectId: 'nazra-274ec',
    storageBucket: 'nazra-274ec.firebasestorage.app',
    iosBundleId: 'com.example.nazra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwMvIasJ_vKHMntyIAJYBqdHjNnhacVgI',
    appId: '1:707222535071:web:fe0b17f186d273fe1e1baa',
    messagingSenderId: '707222535071',
    projectId: 'nazra-274ec',
    authDomain: 'nazra-274ec.firebaseapp.com',
    storageBucket: 'nazra-274ec.firebasestorage.app',
    measurementId: 'G-61S4JRFTDJ',
  );
}
